version: "3.7"

services:
  web:
    build: ./web
    ports:
      - 8080:80
    volumes:
      - ./app/:/var/www/html/
    depends_on:
      - mysql

  mysql:
    build: ./mysql/    
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass